import {
  AiOutlineLink,
  AiFillStar,
  AiOutlineTwitter,
  AiFillInstagram,
  AiTwotoneSetting,
  AiOutlineGift,
  AiTwotoneEdit,
  AiOutlineHeart,
  AiOutlinePlus,
  AiOutlineUserDelete,
  AiFillCloseCircle,
} from 'react-icons/ai';
import { BiTimeFive, BiWalletAlt } from 'react-icons/bi';
import {
  FaWallet,
  FaExchangeAlt,
  FaUserCircle,
  FaChevronRight,
  FaChevronLeft,
} from 'react-icons/fa';
import {
  MdDelete,
  MdDoneAll,
  MdAddAPhoto,
  MdModeEditOutline,
  MdLocalOffer,
} from 'react-icons/md';
import {
  IoMdClose,
  IoMdTrash,
  IoIosWarning,
  IoIosArrowForward,
  IoIosArrowDown,
} from 'react-icons/io';
import { CgSandClock } from 'react-icons/cg';
import { GrFacebookOption, GrPowerCycle } from 'react-icons/gr';
import { GoLocation } from 'react-icons/go';
import {
  HiOutlineMail,
  HiOutlineSearch,
  HiOutlineLightBulb,
} from 'react-icons/hi';
import { TbFileInvoice } from 'react-icons/tb';
import { FiSettings, FiHeart, FiEdit, FiTrash } from 'react-icons/fi';
import {
  RiAuctionFill,
  RiAuctionLine,
  RiEarthFill,
  RiNotification4Line,
  RiArrowDownSFill,
  RiUserFill,
  RiLockPasswordLine,
} from 'react-icons/ri';
import {
  BsArrowClockwise,
  BsCheck2Circle,
  BsXCircleFill,
  BsCalendar3,
  BsFillFileEarmarkTextFill,
  BsFillHeartFill,
  BsHeart,
  BsTag,
  BsThreeDotsVertical,
  BsBookmarkStarFill,
  BsThreeDots,
  BsTwitter,
  BsGithub,
  BsDropletHalf,
  BsEyeSlashFill,
  BsEyeFill,
  BsHouseFill,
  BsSun,
  BsShop,
  BsArrowCounterclockwise,
} from 'react-icons/bs';
import { ImEarth, ImFacebook, ImProfile, ImArrowLeft2 } from 'react-icons/im';
import { SiMinutemailer } from 'react-icons/si';
import { VscFoldDown, VscSignOut } from 'react-icons/vsc';
import { BiMoon } from 'react-icons/bi';
import { HiOutlineMenu, HiOutlineDocumentText } from 'react-icons/hi';

export {
  BsCheck2Circle,
  AiOutlineLink,
  BiTimeFive,
  BsXCircleFill,
  AiTwotoneEdit,
  FaWallet,
  MdDelete,
  MdDoneAll,
  CgSandClock,
  GrFacebookOption,
  BsCalendar3,
  GoLocation,
  HiOutlineMail,
  AiOutlineTwitter,
  AiFillInstagram,
  MdAddAPhoto,
  MdLocalOffer,
  AiTwotoneSetting,
  AiOutlineGift,
  AiFillStar,
  TbFileInvoice,
  FiSettings,
  RiAuctionFill,
  RiAuctionLine,
  BsFillFileEarmarkTextFill,
  BsFillHeartFill,
  BsTag,
  BsThreeDotsVertical,
  BsBookmarkStarFill,
  BsThreeDots,
  ImEarth,
  IoMdClose,
  IoMdTrash,
  IoIosWarning,
  MdModeEditOutline,
  AiOutlinePlus,
  BsTwitter,
  ImFacebook,
  RiEarthFill,
  BsGithub,
  SiMinutemailer,
  ImProfile,
  ImArrowLeft2,
  FiHeart,
  RiNotification4Line,
  BiWalletAlt,
  RiArrowDownSFill,
  FiEdit,
  BsDropletHalf,
  IoIosArrowForward,
  HiOutlineMenu,
  BsHeart,
  HiOutlineDocumentText,
  AiOutlineHeart,
  VscFoldDown,
  GrPowerCycle,
  BsEyeSlashFill,
  BsEyeFill,
  BsHouseFill,
  BsSun,
  BiMoon,
  BsArrowCounterclockwise,
  FaExchangeAlt,
  FaUserCircle,
  RiUserFill,
  BsShop,
  AiOutlineUserDelete,
  RiLockPasswordLine,
  HiOutlineSearch,
  FaChevronRight,
  FaChevronLeft,
  AiFillCloseCircle,
  IoIosArrowDown,
  VscSignOut,
  FiTrash,
  BsArrowClockwise,
  HiOutlineLightBulb,
};
